#!/bin/bash -e
export KUBERNETES_RELEASE_VERSION=v0.13.2
export ETCD_VERSION=v2.0.5
export KUBERNETES_CLUSTER_ID=democluster

export DEFAULT_CONFIG_PATH=/etc/default
export ETCD_EXECUTABLE_LOCATION=/usr/bin
export ETCD_PORT=4001
export KUBERNETES_DOWNLOAD_PATH=/tmp
export KUBERNETES_EXTRACT_DIR=$KUBERNETES_DOWNLOAD_PATH/kubernetes
export KUBERNETES_DIR=$KUBERNETES_EXTRACT_DIR/kubernetes
export KUBERNETES_SERVER_BIN_DIR=$KUBERNETES_DIR/server/kubernetes/server/bin
export KUBERNETES_EXECUTABLE_LOCATION=/usr/bin
export KUBERNETES_MASTER_HOSTNAME=$KUBERNETES_CLUSTER_ID-master
export KUBERNETES_SLAVE1_HOSTNAME=$KUBERNETES_CLUSTER_ID-node1
export KUBERNETES_SLAVE2_HOSTNAME=$KUBERNETES_CLUSTER_ID-node2